### POST
POST http://localhost:5001/notes
Content-Type: application/json

{
    "content": "Psalms 16:6 = Lines are fallen unto me in pleasant places.Yea, i have a godly heritage."
}

###GET ALL TODOS

GET http://localhost:5001/notes/
Content-Type: text/html

### DELETE TODO

DELETE http://localhost:5001/notes/68094839b21f39b73979b454
Content-Type: application/json

{
    "content":"It didn't work. ID is fixed"
}

###
PUT http://localhost:5001/notes/68094839b21f39b73979b454
Content-Type: application/json

{
    "content":"I just updated this"
}

###
POST http://localhost:5001/api/users/register
Content-Type: application/json

{
    "name":"Godwin",
    "email":"gwindev@gmail.com",
    "password":"okoeguale"
}