### POST
POST http://localhost:5000/notes
Content-Type: application/json

{
    "title": "Watching Hunter X Hunter",
    "content": "Hunter X Hunter is an anime"
}

###GET ALL TODOS

GET http://localhost:5000/notes
Content-Type: text/html

### DELETE TODO

DELETE http://localhost:5000/notes/680674082fe78f50392c6f03