### POST
POST http://localhost:5001/notes
Content-Type: application/json

{
    "content": "My Wife will be arriving tomorrow. I am so excited"
}

###GET ALL TODOS

GET http://localhost:5001/notes
Content-Type: text/html

### DELETE TODO

DELETE http://localhost:5001/notes/6807be40c9024a6cbdabde9a
Content-Type: application/json

{
    "content":"It didn't work. ID is fixed"
}

###
PUT http://localhost:5001/notes/6807be40c9024a6cbdabde9a
Content-Type: application/json

{
    "content":"I just updated this"
}